version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./server/database:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: matcha
      POSTGRES_DB: matcha
  api:
    build: ./server
    volumes:
      - ${GOPATH}/src:/go/src
      - ./server:/matcha/server
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: matcha
      POSTGRES_DB: matcha
    ports:
    - "81:81"
    depends_on:
    - db
    links:
    - db
