version: '3.5'
services:
  neo4j:
    image: neo4j:latest
    container_name: 'neo4j'
    volumes:
    - ./neo4j/data:/data
    - ./neo4j/conf/:/conf
    ports:
    - 7474:7474
    - 7687:7687
    restart: on-failure
    networks:
    - neo4j_go_net

  api:
    build: ./server
    container_name: 'api'
    volumes:
      - ${GOPATH}/src:/go/src
      - ./server:/matcha/server
    ports:
    - "81:81"
    depends_on:
      - neo4j
      - web
    tty: true
    links:
      - neo4j
    networks:
      - default
    restart: unless-stopped

  web:
    build: ./client
    container_name: 'web'
    volumes:
    - ./client:/app
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    tty: true
    working_dir: /app
    command: sh run.sh

networks:
  default:
    driver: bridge
  neo4j_go_net:
    driver: bridge

volumes:
    neo4j:
    api:
