version: '3.5'
services:
  neo4j:
    image: neo4j:latest
    container_name: 'neo4j'
    volumes:
    - ./neo4j/data:/data
    - ./neo4j/conf/:/conf
    ports:
    - 7474:7474
    - 7687:7687
    restart: on-failure
    networks:
    - default

  api:
    build: api
    container_name: 'api'
    volumes:
      - ${GOPATH}/src:/go/src
      - ./api:/matcha/api
      - ./client/src/public/img:/public/img
    ports:
    - "8181:81"
    depends_on:
      - neo4j
      - web
    environment:
      NEO_HOST: neo4j
    tty: true
    links:
      - neo4j
    networks:
      - default
    restart: unless-stopped

  web:
    build: ./client
    container_name: 'web'
    volumes:
    - ./client:/app
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    tty: true
    working_dir: /app
    command: sh run.sh
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
    neo4j:
    api: