version: '3.5'
services:
  postgres:
    image: postgres
    volumes:
    - ./db/init:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: matcha
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: matcha
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - default
    tty: true
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: abbenham@student.42.fr
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "82:80"
    networks:
      - default
    tty: true
    restart: unless-stopped

  api:
    build: ./server
    volumes:
      - ${GOPATH}/src:/go/src
      - ./server:/matcha/server
    ports:
    - "81:81"
    depends_on:
      - postgres
      - web
    tty: true
    links:
      - postgres
    networks:
      - default
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=postgres
  web:
    build: ./client
    volumes:
    - ./client:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    tty: true
    working_dir: /app
    command: sh run.sh
networks:
  default:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    api:
