version: '3.5'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: matcha
      POSTGRES_PASSWORD: secret
      PGDATA: /data/postgres
    volumes:
       - ./server/database:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - default
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: abbenham@student.42.fr
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "82:80"
    networks:
      - default
    restart: unless-stopped

  api:
    build: ./server
    volumes:
      - ${GOPATH}/src:/go/src
      - ./server:/matcha/server
    ports:
    - "81:81"
    depends_on:
      - postgres
      - web
    links:
      - postgres
    networks:
      - default
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=matcha_postgres_1
  web:
    build: ./client
    volumes:
    - ./client:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    command: npm run dev
networks:
  default:
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.33.0.0/16
    driver: bridge

volumes:
    postgres:
    pgadmin:
    api:
